#!/bin/sh
while IFS='' read -r line || [[ -n "$line" ]]; do
  [[ "$line" =~ ^(#|[A-Z]+-[0-9]+:?[[:space:]]*$) || -z "${line// }" ]] && continue
  exit 0
done < "$1"
echo "Aborting commit; you did not edit the message."
exit 1
