#!/bin/bash
BRANCH_PATH=$(git symbolic-ref -q HEAD)
# Attempt to pull the JIRA ticket number from the name of the current branch if
# the ticket number isn't already in the first line of the commit message.
TICKET_PATTERN='[A-z]+[0-9]*-[0-9]+'
if [[ "${BRANCH_PATH}" =~ (${TICKET_PATTERN}) ]]; then
  TICKET_ID="${BASH_REMATCH[0]}"
  if [[ "${TICKET_ID}" && ! $(grep -Ei ^${TICKET_ID} $1) ]]; then
    # Prepend the commit message with the JIRA number.
    MESSAGE='# Jira Ticket: ['$(echo "${TICKET_ID}" | tr [a-z] [A-Z])']'
    printf '%s\n%s' "${MESSAGE}" "$(cat ${1})" > $1
  fi
  exit 0
fi
